### ISSUE TITLE
Vamos reformular o readme

### ISSUE THREAD

**Issue by KatyaPalheta** [VanelliMendes/Calculadora#1]
Vou mandar pra vc um modelo de readme para vc escrever e colocar informações sobre o projeto.
[readme.docx](https://github.com/VanelliMendes/Calculadora/files/9600517/readme.docx)

**Comment by VanelliMendes** [comment]
Ok, grata pela sua contribuição. Reformularei assim que puder.
Sinta-se livre para me ajudar sempre . Amo orientações.
